### ISSUE TITLE
Add possibility to set parameters not only in console mode

### ISSUE THREAD

**Issue by ruadmjn** [devopshq/FuzzyClassificator#11]
import FuzzyClassificator as FC
FC.Main(<here will be params>)

**Comment by Tim55667757** [comment]
Since versions **1.2.dev52** and more newest you can use FuzzyClassificator's API Main() functions if it imported as module in your scripts. Also FuzzyClassificator's API work in python interpreter too.

API in README updated (See chapters: "API example to run Learning mode", "API example to run Classifying mode" and "Another API parameters"). 

It is helped? Please report new bugs or the required functionality in new tasks.

---
Some examples are below.

API use Main() function to work with both mode. The learnParameters in Main() used first and classifyParameters used second. If some of them defined they used with high priority than CLI parameters.

Also you can use API Main() function to run Classify mode right after Learning mode.


**When you run Learning mode in CLI, for example:**
```
python FuzzyClassificator.py --debug-level=info -u 1 --learn config=3,3,2,2 epochs=100 rate=0.5 momentum=0.5 epsilon=0.75 stop=1
```

**Also you can run the same Learning mode command using API:**
```
import FuzzyClassificator as FC
import FCLogger

FCLogger.SetLevel("info")
FC.epochsToUpdate = 1
parameters = {
    "config": "3,3,2,2",
    "epochs": 10,
    "rate": 0.5,
    "momentum": 0.4,
    "epsilon": 0.75,
    "stop": 1
}
FC.Main(learnParameters=parameters)  # Learning mode
```

**When you run Classifying mode in CLI, for example:**
```
python FuzzyClassificator.py --candidates candidates.dat --network network.xml --report report.txt  --separator=TAB --debug-level=DEBUG --classify config=3,3,2,2
```

**Also you can run the same Classifying mode command using API:**
```
import FuzzyClassificator as FC
from FCLogger import SetLevel

FC.candidatesDataFile = "candidates.dat"
FC.neuroNetworkFile = "network.xml"
FC.reportDataFile = "report.txt"
FC.sepSymbol = "TAB"
SetLevel("DEBUG")
parameters = {
    "config": "3,3,2,2",
}
FC.Main(classifyParameters=parameters)  # Classifying mode
```
